CREATE TABLE IF NOT EXISTS state_machine_instance (
    machine_type VARCHAR(128) NOT NULL,
    machine_id   VARCHAR(128) NOT NULL,
    state        VARCHAR(128) NOT NULL,
    context      JSONB,
    version      BIGINT NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (machine_type, machine_id)
);

CREATE TABLE IF NOT EXISTS state_machine_event (
    event_id      VARCHAR(128) NOT NULL,
    machine_type  VARCHAR(128) NOT NULL,
    machine_id    VARCHAR(128) NOT NULL,
    event_type    VARCHAR(128) NOT NULL,
    from_state    VARCHAR(128) NOT NULL,
    to_state      VARCHAR(128) NOT NULL,
    result        VARCHAR(32) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (event_id),
    CONSTRAINT chk_state_machine_event_result
        CHECK (result IN ('success', 'rejected'))
);

CREATE INDEX IF NOT EXISTS idx_state_machine_event_machine
    ON state_machine_event (machine_type, machine_id, created_at);

CREATE TABLE IF NOT EXISTS state_machine_request (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id       VARCHAR(128) NOT NULL,
    machine_type   VARCHAR(128) NOT NULL,
    machine_id     VARCHAR(128) NOT NULL,
    event_type     VARCHAR(128) NOT NULL,
    payload        JSONB,
    status         INT NOT NULL,
    retry_count    INT NOT NULL DEFAULT 0,
    locked_by      VARCHAR(128),
    locked_until   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at   TIMESTAMPTZ,
    PRIMARY KEY (id),
    UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_sm_request_recovery
    ON state_machine_request (status, locked_until)
    WHERE status IN (0, 1, 2);
